In [1]:
import torch

x = torch.arange(2, 7)
print(x)

tensor([2, 3, 4, 5, 6])


In [2]:
torch.arange(0,4)

tensor([0, 1, 2, 3])

In [2]:
import torch
x = torch.arange(10) * 10
print(x)

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


In [4]:
x[3].item()

30

In [6]:
torch.equal?

Docstring:
equal(input, other) -> bool

``True`` if two tensors have the same size and elements, ``False`` otherwise.

.. note::

    Tensors containing NaNs are never equal to each other. Additionally, this function does not
    differentiate between the data types of the tensors during comparison. For more thorough tensor checks,
    use :meth:`torch.testing.assert_close`.

Example::

    >>> torch.equal(torch.tensor([1, 2]), torch.tensor([1, 2]))
    True
    >>> torch.equal(torch.tensor([3, torch.nan]), torch.tensor([3, torch.nan]))
    False
    >>> torch.equal(torch.tensor([1, 2, 3], dtype=torch.int32), torch.tensor([1, 2, 3], dtype=torch.float32))
    True
Type:      builtin_function_or_method

In [1]:
import torch

t = torch.arange(10)
print("t            :", t)
print("t[3]         :", t[3].item())          # single element
print("t[2:5]       :", t[2:5])                # slice

assert t[3].item() == 3
assert torch.equal(t[2:5], torch.tensor([2, 3, 4]))
print("OK: plain indexing/slicing behave as expected")

t            : tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
t[3]         : 3
t[2:5]       : tensor([2, 3, 4])
OK: plain indexing/slicing behave as expected


In [3]:
t = torch.arange(10) * 10
idx = torch.tensor([1,3,5])

In [8]:
t[[0,2,3]]

tensor([ 0, 20, 30])

In [9]:
mat = torch.arange(12).reshape(3, 4)
print("mat:\n", mat)

mat:
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [20]:
mat[2,2]

tensor(10)

In [25]:
mat = torch.arange(12).reshape(3,4)
print(mat.shape)

torch.Size([3, 4])


In [26]:
mat[[0,1,1],[3,3,2]]

tensor([3, 7, 6])

In [27]:
mat

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [29]:
mat[:, [1,1,3]]

tensor([[ 1,  1,  3],
        [ 5,  5,  7],
        [ 9,  9, 11]])

In [30]:
mat = torch.arange(12).reshape(3, 4)

row_idx = torch.tensor([0, 1, 2]).unsqueeze(1)  # shape (3, 1)
col_idx = torch.tensor([0, 2]).unsqueeze(0)      # shape (1, 2)

In [34]:
mat

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [38]:
print(mat[1][2])
print(mat[1,2])
print(mat[(1,2)])

tensor(6)
tensor(6)
tensor(6)


In [31]:
row_idx

tensor([[0],
        [1],
        [2]])

In [40]:
mat[row_idx]

tensor([[[ 0,  1,  2,  3]],

        [[ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11]]])

In [32]:
col_idx

tensor([[0, 2]])

In [33]:
mat[row_idx, col_idx]

tensor([[ 0,  2],
        [ 4,  6],
        [ 8, 10]])

In [44]:
row_idx = [0, 1, 2]
col_idx = [3, 0, 1]

mat[row_idx, col_idx]

tensor([3, 4, 9])

In [45]:
mat

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [46]:
row_idx = torch.tensor([0, 1, 2]).unsqueeze(1)  # shape (3, 1)
col_idx = torch.tensor([0, 2]).unsqueeze(0)      # shape (1, 2)

print(row_idx)
print(col_idx)

tensor([[0],
        [1],
        [2]])
tensor([[0, 2]])


In [47]:
row_b, col_b = torch.broadcast_tensors(row_idx, col_idx)
print(row_b)
print(col_b)

tensor([[0, 0],
        [1, 1],
        [2, 2]])
tensor([[0, 2],
        [0, 2],
        [0, 2]])


In [48]:
mat

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])